---
#
# Ping host with default parameters. Fails if any packets lost.
#
- name: 'Ping host or IP with default parameters. Fails if any packets lost.'
  hosts: "{{ host_name }}"
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: 'Ping host or IP with default parameters. Fails if any packets lost.'
      juniper_junos_ping:
        dest: "{{ destination_IP }}"
      register: response

    - name: "Print the response"
      debug:
        var: response
