---
#
# The old way.
# Explicit user and passwd
#
- name: 'Explicit auth arguments'
  hosts: DOCKERSWITH.CBADOPS.NET
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        user: "astronaut"
        passwd: "n3wp@ss!"

    - name: "Print Junos Version"
      debug:
        var: junos.version
