---
#
# Aliases for the arguments used by the core modules.
#
- name: 'Aliases for core argument names'
  hosts: DOCKERSWITCH.CBADOPS.NET
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        username: "astronaut"
        password: "n3wp@ss!"

    - name: "Print Junos Version"
      debug:
        var: junos.version
