---
#
# All connection-related arguments may be specified
# insider a provider dictionary, like the core modules.
#
- name: 'Provider dict for connection arguments'
  hosts: DOCKERSWITCH.CBADOPS.NET
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        provider:
          username: "astronaut"
          password: "n3wp@ss!"

    - name: "Print Junos Version"
      debug:
        var: junos.version
