---
#
# The old way.
# Explicit host argument set to {{ inventory_hostname }}
#
- name: 'Explicit host argument'
  hosts: DOCKERSWITCH.CBADOPS.NET
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        host: "{{ inventory_hostname }}"
        user: "astronaut"
        passwd: "n3wp@ss!"

    - name: "Print Junos Version"
      debug:
        var: junos.version
