---
#
# The new way.
# host argument defaults to {{ inventory_hostname }}
#
- name: 'Implicit host argument'
  hosts: DOCKERSWITCH.CBADOPS.NET
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        user: "astronaut"
        passwd: "n3wp@ss!"

    - name: "Print Junos Version"
      debug:
        var: junos.version
